export const puzzles = [
	{
		difficulty: 'learn',
		board: '1~R3|3|_O_____B_',
		hint: 'The object of the game is to make the cows come home.\n Click on the cow, then click on the barn to bring it home.'
	},
	{
		difficulty: 'learn',
		board: '4~R3|3|O__O__BOO',
		hint: "If there is more than one cow, you have to bring all of them home.\n Cows can't jump over each other, so you have to move the cows closer to the home first."
	},
	{
		difficulty: 'learn',
		board: '6~H3|3|_OOOBO_OO',
		hint: 'Some cows live in a hexagonal world.\n They also need to come home.'
	},
	{
		difficulty: 'learn',
		board: '2~R3|3|P____BO__',
		hint: 'Farmers can help guide the cows home.\n Click on the cow, then click on the farmer, then click on the barn.'
	},
	{
		difficulty: 'learn',
		board: '6~H3|3|_P___POEB',
		hint: "It's impossible travel through empty spaces.\n The cow needs to find a more indirect way to come home."
	},
	{
		difficulty: 'learn',
		board: '3~R3|3|P_P__B_O_',
		hint: 'Farmers can pull each other. \n One of the farmers will need to move to help the cow come home.'
	},
	{
		difficulty: 'learn',
		board: '3~R3|3|O_O___BB_',
		hint: 'Cows can also pull each other.'
	},
	{
		difficulty: 'learn',
		board: '2~H3|3|_B_P_PO__',
		hint: 'The farmer will have to move out of the way to let the cow come home.'
	},
	{
		difficulty: 'learn',
		board: '4~R3|4|OP___B__PP_',
		hint: 'This cow will need the help of all the farmers to find its way home.'
	},
	{
		difficulty: 'learn',
		board: '4~R3|2|PPHBOO',
		hint: 'Cows live in barns. Farmers live in houses.\n When you see a house, it means the farmers need to come home too.'
	},
	{
		difficulty: 'learn',
		board: '3~H4|3|H_O____B_P__',
		hint: 'Who should go home first, the cow or the farmer?'
	},
	{
		difficulty: 'learn',
		board: '3~R3|4|O____PP__B__',
		hint: 'Oh no, the farmer is blocking the cow! \n What can we do?'
	},
	{
		difficulty: 'learn',
		board: '6~R4|3|__P_O____B_P',
		hint: "Farmers don't live in barns, but they can still move towards them."
	},
	{
		difficulty: 'learn',
		board: '5~H4|3|OO_P____B__H',
		hint: "Sometimes you need to be patient. \n Just because a cow can come home right away, doesn't mean it should."
	},
	{
		difficulty: 'learn',
		board: '5~R4|3|O_O____BP__P',
		hint: "I think you've got the hang of this now.\nIf you can solve this, you're ready for the next level."
	},
	{ difficulty: 'easy', board: '6~R4|2|_BH_OP_P' },
	{ difficulty: 'easy', board: '4~H3|3|BB___OHP_' },
	{ difficulty: 'easy', board: '4~R4|2|_B_PO_H_' },
	{ difficulty: 'easy', board: '4~H4|3|BO_H_______P' },
	{ difficulty: 'easy', board: '4~R3|3|_B_H_O_P_' },
	{ difficulty: 'easy', board: '4~H3|3|OB___P_H_' },
	{ difficulty: 'easy', board: '4~R4|3|_B__B_H_O__P' },
	{ difficulty: 'easy', board: '4~H4|3|_B_PH__B___O' },
	{ difficulty: 'easy', board: '4~R4|3|B_B__H_OP___' },
	{ difficulty: 'easy', board: '4~H5|3|BP__O_______BH_' },
	{ difficulty: 'easy', board: '4~R4|3|B__P__B__H_O' },
	{ difficulty: 'easy', board: '6~H3|3|_BOH__O_P' },
	{ difficulty: 'easy', board: '6~R3|3|BB___HPPO' },
	{ difficulty: 'easy', board: '4~H5|3|BO_P_____H___B_' },
	{ difficulty: 'easy', board: '8~R4|3|OP_P_BH_O___' },
	{ difficulty: 'easy', board: '6~H4|4|B_H_O______OP___' },
	{ difficulty: 'easy', board: '6~R4|3|_BO_H____P_P' },
	{ difficulty: 'easy', board: '6~H5|3|B_P_O_____O___H' },
	{ difficulty: 'easy', board: '7~R4|3|_BB_O__O_HP_' },
	{ difficulty: 'easy', board: '6~H4|3|B_P__H__O__P' },
	{ difficulty: 'easy', board: '12~R4|3|PBO__H_BOOOO' },
	{ difficulty: 'easy', board: '6~H4|4|_B_P______B_PH_O' },
	{ difficulty: 'easy', board: '8~R4|3|HPB_O__OOB__' },
	{ difficulty: 'easy', board: '8~H4|3|BO_PHB__O__O' },
	{ difficulty: 'easy', board: '10~R5|3|OOP_PBB_H___P__' },
	{ difficulty: 'easy', board: '8~H5|3|BPP_PHB_______O' },
	{ difficulty: 'easy', board: '8~R6|3|O__PP_BH___B__O___' },
	{ difficulty: 'easy', board: '7~H4|3|B_OH___BP_O_' },
	{ difficulty: 'easy', board: '9~R5|3|_B_____BH_OPP_O' },
	{ difficulty: 'easy', board: '8~H5|3|PB____HB__P__PO' },
	{ difficulty: 'moderate', board: '12~R5|3|B_POOH_____P_P_' },
	{ difficulty: 'moderate', board: '9~H5|3|B_PO_____P__BH_' },
	{ difficulty: 'moderate', board: '11~R4|4|_B__B__P__H_PPOP' },
	{ difficulty: 'moderate', board: '12~H5|3|BOH__P_B___OPPP' },
	{ difficulty: 'moderate', board: '13~R5|3|BPO_HOB____OO_O' },
	{ difficulty: 'moderate', board: '8~H4|4|PBH____O___O_B__' },
	{ difficulty: 'moderate', board: '11~R5|3|B_OB___H_OPP__P' },
	{ difficulty: 'moderate', board: '13~H5|3|B_PO____H_O_POO' },
	{ difficulty: 'moderate', board: '11~R4|4|_B_P__HO_B_PO__P' },
	{ difficulty: 'moderate', board: '13~H5|3|B_H___B_PPOPP_O' },
	{ difficulty: 'moderate', board: '14~R4|4|HOP____OO_BBO_O_' },
	{ difficulty: 'moderate', board: '14~H5|3|OP_OP_BH__OP__P' },
	{ difficulty: 'moderate', board: '14~R5|3|EHOBPB______PPP' },
	{ difficulty: 'moderate', board: '12~H5|3|EBH_O_____PO_PE' },
	{ difficulty: 'moderate', board: '18~R6|3|BOEP_____P_PPPOBH_' },
	{ difficulty: 'moderate', board: '16~H5|3|BPBHO___OPOEO_O' },
	{ difficulty: 'moderate', board: '15~R6|3|B__OE__BH___PPOO_P' },
	{ difficulty: 'moderate', board: '16~H5|3|B_P_PB_HP_EPOOO' },
	{ difficulty: 'moderate', board: '17~R6|3|_OBPPP_B_PE_O_HP__' },
	{ difficulty: 'moderate', board: '14~H5|3|B_PBPE___PPO_HO' },
	{ difficulty: 'moderate', board: '11~R6|3|B___PPB___E__H_OO_' },
	{ difficulty: 'moderate', board: '15~H5|3|EB__OHPPP_PO__O' },
	{ difficulty: 'moderate', board: '16~R4|4|PBBPH__P____OPEP' },
	{ difficulty: 'moderate', board: '15~H5|3|B_POP____OEP_BH' },
	{ difficulty: 'moderate', board: '19~R5|3|EPBOPHP___P__PO' },
	{ difficulty: 'moderate', board: '13~H6|3|BO____H____O_POOPB' },
	{ difficulty: 'moderate', board: '18~R4|4|EEBP_O_O_H__POPP' },
	{ difficulty: 'moderate', board: '17~H5|3|B_O_HPO__OOP_BO' },
	{ difficulty: 'moderate', board: '17~R6|3|EEBOOP_H____OO__O_' },
	{ difficulty: 'moderate', board: '16~H6|3|E__OOO_B___POPPOE_' },
	{ difficulty: 'hard', board: '20~R6|3|BBOPPEO______HOO_O' },
	{ difficulty: 'hard', board: '18~H6|3|EPOOP_O_H_O_P_BB_P' },
	{ difficulty: 'hard', board: '20~R6|3|EP_OBPOOO_H_P_PB_P' },
	{ difficulty: 'hard', board: '21~H6|3|EP_EO_PP___OPBOH_P' },
	{ difficulty: 'hard', board: '22~R6|3|__BEPOH__OPP__BOOO' },
	{ difficulty: 'hard', board: '19~H6|3|OEOB_PPP___PO_PH_O' },
	{ difficulty: 'hard', board: '21~R6|3|EOHBO__PO_BOO__P_P' },
	{ difficulty: 'hard', board: '20~H4|4|BB___POHPPOO__PP' },
	{ difficulty: 'hard', board: '22~R6|3|EPO__OOB__PBPO_H_O' },
	{ difficulty: 'hard', board: '21~H6|3|PB__PO__OPE_O_HBPP' },
	{ difficulty: 'hard', board: '22~R6|3|EP_PB_E_P__OOOOH__' },
	{ difficulty: 'hard', board: '20~H6|3|EP_OO__B_H__O__PPO' },
	{ difficulty: 'hard', board: '23~R6|3|EOH_OOPPOP_BO__PB_' },
	{ difficulty: 'hard', board: '20~H6|3|B_PPOE___OPB_P_H_P' },
	{ difficulty: 'hard', board: '23~R6|3|OOP__PBH__B_P__OOP' },
	{ difficulty: 'hard', board: '19~H4|4|B_BO___PO__OPH_P' },
	{ difficulty: 'hard', board: '22~R6|3|B__P_PH_OOO__BPEOO' },
	{ difficulty: 'hard', board: '21~H4|4|EB_OP__HP_O_O__O' },
	{ difficulty: 'hard', board: '23~R6|3|B__POOOB__H_OPO__P' },
	{ difficulty: 'hard', board: '25~H6|3|_BPPOOP_OO_EPEHO__' },
	{ difficulty: 'hard', board: '26~R6|3|B_PEBPPHO__OP__OOO' },
	{ difficulty: 'hard', board: '21~H6|3|PBOH_O______O_P__O' },
	{ difficulty: 'hard', board: '27~R6|3|BEOBHP___PO_PP_P_O' },
	{ difficulty: 'hard', board: '23~H6|3|PBHOOO____E_PBP__P' },
	{ difficulty: 'hard', board: '29~R6|3|EHBPBOP__OPPO_O__P' },
	{ difficulty: 'hard', board: '27~H4|4|B_OE_POO__HOO_P_' },
	{ difficulty: 'hard', board: '25~R6|3|B_OO_OP__OPPEHB_P_' },
	{ difficulty: 'hard', board: '29~H4|4|BHOE_PPOP_EOP_P_' },
	{ difficulty: 'hard', board: '25~R6|3|OH_O_P____O_PPBBOP' },
	{ difficulty: 'hard', board: '27~H4|4|EP___PPBOOO_OE_O' },
	{ difficulty: 'insane', board: '32~R6|3|EOBHPOEP__POP__O_O' },
	{ difficulty: 'insane', board: '28~H4|4|B__P_POO__OHP_PE' },
	{ difficulty: 'insane', board: '30~R6|3|PPBHOOB_PO_EP_P__O' },
	{ difficulty: 'insane', board: '30~H4|4|B__O_PP___OOPO_H' },
	{ difficulty: 'insane', board: '32~R6|3|OBB_HP__PO__OPOP_P' },
	{ difficulty: 'insane', board: '31~H4|4|B_P__OOO_PHOP_PE' },
	{ difficulty: 'insane', board: '29~R6|3|OBH_B_PO____P_POOO' },
	{ difficulty: 'insane', board: '31~H4|4|E_BP__HOP_P_POOO' },
	{ difficulty: 'insane', board: '31~R6|3|EOBHPO_PP___P_P__O' },
	{ difficulty: 'insane', board: '29~H4|4|BHOO_P___P__PE_O' },
	{ difficulty: 'insane', board: '31~R6|3|EBHO_PB_OPOPPP___O' },
	{ difficulty: 'insane', board: '32~H4|4|H__P_OPB__PPO_BP' },
	{ difficulty: 'insane', board: '30~R6|3|EBHO_PB__POPPP___O' },
	{ difficulty: 'insane', board: '25~H4|4|BPBHPP__O__O__O_' },
	{ difficulty: 'insane', board: '28~R6|3|EB_HBO_____POOOP_P' },
	{ difficulty: 'insane', board: '35~H4|4|BOHO_POOP_P___O_' },
	{ difficulty: 'insane', board: '34~R6|3|B_PBHPPPO___P_O_OO' },
	{ difficulty: 'insane', board: '38~H4|4|BE_P_PO___OOOPHO' },
	{ difficulty: 'insane', board: '34~R6|3|BHBPPE_O_O__POOP_P' },
	{ difficulty: 'insane', board: '37~H4|4|BHOE_POO_P_OP_O_' },
	{ difficulty: 'insane', board: '31~R6|3|BHB_P__O_O__POOP_P' },
	{ difficulty: 'insane', board: '28~H4|4|PBEP___PH__O__PO' },
	{ difficulty: 'insane', board: '35~R6|3|OBHP_OPPO___PP___O' },
	{ difficulty: 'insane', board: '36~H4|4|BH_O_OPOP__OP__E' },
	{ difficulty: 'insane', board: '33~R6|3|PPBHOO______O_PO_P' },
	{ difficulty: 'insane', board: '38~H4|4|BHO____OPOP_PE_O' },
	{ difficulty: 'insane', board: '35~R6|3|OBHP_O___POOPP___O' },
	{ difficulty: 'insane', board: '36~H4|4|BH_O_OPOP__OP___' },
	{ difficulty: 'insane', board: '35~R6|3|PPBHOO____P_O_P_OP' },
	{ difficulty: 'insane', board: '36~H4|4|BH_O_OPOP__OP__E' }
];
